import { useEffect, useMemo, useRef, useState } from "react";
import { useMovement } from "./hooks/useMovement";
import { useWebRTC } from "./hooks/useWebRTC";
import WorldCanvas from "./components/WorldCanvas";
import { socket } from "./socket/index";
import { AUDIO_RADIUS, WORLD_HEIGHT, WORLD_WIDTH } from "./constants/world";

function Icon({ name, size = 20 }) {
  const common={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round",strokeLinejoin:"round","aria-hidden":true};
  const paths={
    home:<><path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9"/><path d="M9 20v-6h6v6"/></>,
    people:<><path d="M16 21v-2a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v2"/><circle cx="9.5" cy="7" r="4"/><path d="M17 11a4 4 0 0 0 0-8"/><path d="M21 21v-2a4 4 0 0 0-3-3.87"/></>,
    map:<><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3Z"/><path d="M9 3v15"/><path d="M15 6v15"/></>,
    settings:<><circle cx="12" cy="12" r="3.5"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-1.7 1.7-.06-.06a1.7 1.7 0 0 0-1.88-.34A1.7 1.7 0 0 0 15.13 19v1h-2.4v-1a1.7 1.7 0 0 0-1.03-1.56 1.7 1.7 0 0 0-1.88.34l-.06.06-1.7-1.7.06-.06A1.7 1.7 0 0 0 8.46 15a1.7 1.7 0 0 0-1.56-1.03H6v-2.4h.9A1.7 1.7 0 0 0 8.46 10a1.7 1.7 0 0 0-.34-1.88l-.06-.06 1.7-1.7.06.06a1.7 1.7 0 0 0 1.88.34A1.7 1.7 0 0 0 12.73 5V4h2.4v1a1.7 1.7 0 0 0 1.03 1.56 1.7 1.7 0 0 0 1.88-.34l.06-.06 1.7 1.7-.06.06A1.7 1.7 0 0 0 19.46 10c.2.62.78 1.03 1.44 1.03H21v2.4h-.22A1.7 1.7 0 0 0 19.4 15Z"/></>,
    link:<><path d="M10 13a5 5 0 0 0 7.07.07l2-2A5 5 0 0 0 12 4l-1 1"/><path d="M14 11a5 5 0 0 0-7.07-.07l-2 2A5 5 0 0 0 12 20l1-1"/></>,
    copy:<><rect x="9" y="9" width="10" height="10" rx="2"/><path d="M15 9V7a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2"/></>,
    mic:<><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3M8 21h8"/></>,
    micOff:<><path d="M9 9V6a3 3 0 0 1 5.7-1.3"/><path d="M15 10v1a3 3 0 0 1-5.3 1.9"/><path d="M5 11a7 7 0 0 0 10.9 5.8M12 18v3M8 21h8"/><path d="m3 3 18 18"/></>,
    search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>
  };
  return <svg {...common}>{paths[name]}</svg>;
}
function Brand(){return <div className="workspace-brand"><span className="workspace-brand__mark"><i/><i/><i/></span><span className="workspace-brand__name"><b>Proxy</b><strong>Speak</strong></span><span className="workspace-brand__tagline">Your space. <em>Your people.</em></span></div>}
function GlassButton({children,className="",...props}){return <button className={`glass-button ${className}`} {...props}>{children}</button>}
function Avatar({name="?",tone="green",you=false}){return <span className={`avatar avatar--${tone}${you?" avatar--you":""}`}>{name.slice(0,1).toUpperCase()}</span>}

function JoinWorld({playerName,setPlayerName,inviteCode,setInviteCode,isConnecting,error,onCreate,onJoin}){return <div className="world-gate glass-surface"><div className="world-gate__brand"><span className="workspace-brand__mark"><i/><i/><i/></span><b>Proxy<span>Speak</span></b></div><span className="panel-kicker">PRIVATE SPATIAL WORKSPACE</span><h1>Join a world.<br/><em>Be closer.</em></h1><p>Enter an invite code to join someone’s world, or create your own room and invite people into it.</p><label>Your display name<input value={playerName} onChange={e=>setPlayerName(e.target.value)} maxLength={20} placeholder="e.g. Shivam"/></label><label>World invite code <span className="optional">optional when creating</span><input value={inviteCode} onChange={e=>setInviteCode(e.target.value.toUpperCase())} maxLength={6} placeholder="ABC123"/></label><div className="world-gate__actions"><button className="join-primary" onClick={onJoin} disabled={isConnecting}>{isConnecting?"Joining…":"Join world"} <span>→</span></button><button className="join-secondary" onClick={onCreate} disabled={isConnecting}>Create my world</button></div>{error&&<div className="join-error">{error}</div>}<small>Nothing is loaded as a shared room until you create or join one.</small></div>}
function PeoplePanel({playerName,remotePlayers,onClose}){return <aside className="floating-panel people-panel" data-panel-surface><div className="panel-heading"><div><span className="panel-kicker">PEOPLE IN WORLD</span><h2>{remotePlayers.length+1}</h2></div><GlassButton onClick={onClose}>×</GlassButton></div><div className="people-list"><div className="person-row person-row--you"><Avatar name={playerName} tone="red" you/><div><b>{playerName} <em>YOU</em></b><small>Your position</small></div><span className="person-state person-state--yellow"/></div>{remotePlayers.map(p=><div className="person-row" key={p.playerId}><Avatar name={p.name}/><div><b>{p.name}</b><small>In your world</small></div><span className="person-state person-state--green"/></div>)}</div>{remotePlayers.length===0&&<div className="people-empty">There is no one here yet. Invite someone to your world.</div>}</aside>}
function MiniMap({position,remotePlayers,onClose}){const x=Math.max(3,Math.min(97,(position.x/WORLD_WIDTH)*100));const y=Math.max(3,Math.min(97,(position.y/WORLD_HEIGHT)*100));const rooms=[["Lounge","a"],["Focus","b"],["Meeting","c"],["Social","d"],["Commons","e"],["Quiet","f"],["Work","g"],["Lab","h"],["Archive","i"]];return <aside className="floating-panel map-panel" data-panel-surface><div className="mini-map__top"><div><span className="panel-kicker">WORLD MAP</span><strong>Floor 1 · Live</strong></div><GlassButton onClick={onClose} aria-label="Close map">×</GlassButton></div><div className="mini-map"><div className="mini-map__rooms">{rooms.map(([name,key])=><span key={key} className={`mini-map__room mini-map__room--${key}`}><b>{name}</b></span>)}{remotePlayers.map(player=><i key={player.playerId} className="mini-dot mini-dot--green" title={player.name} style={{left:`${Math.max(3,Math.min(97,(player.x/WORLD_WIDTH)*100))}%`,top:`${Math.max(3,Math.min(97,(player.y/WORLD_HEIGHT)*100))}%`}}/>)}<i className="mini-dot mini-dot--red" style={{left:`${x}%`,top:`${y}%`}}/></div><div className="mini-map__legend"><span><i className="legend-dot legend-dot--red"/> You</span><span><i className="legend-dot legend-dot--green"/> {remotePlayers.length} {remotePlayers.length===1?"person":"people"}</span></div></div></aside>}
function SettingsPanel({transparency,setTransparency,onClose}){return <aside className="floating-panel settings-panel" data-panel-surface><div className="panel-heading"><div><span className="panel-kicker">WORKSPACE</span><h2>Appearance</h2></div><GlassButton onClick={onClose}>×</GlassButton></div><div className="setting-row"><div><b>Glass transparency</b><small>Change how much of the world shows through the interface.</small></div><strong>{Math.round(transparency*100)}%</strong></div><input className="transparency-slider" type="range" min=".35" max=".85" step=".01" value={transparency} onChange={e=>setTransparency(Number(e.target.value))}/><div className="setting-scale"><span>Transparent</span><span>Solid</span></div></aside>}
function TopBar({worldName,connectedCount,activePanel,onPeople,onMap,onSettings,onInvite}){return <header className="workspace-topbar glass-surface"><Brand/><div className="workspace-topbar__center"><div className="workspace-select glass-button" aria-label={`Current world: ${worldName}`}><span className="workspace-thumb">⌂</span><span><b>{worldName}</b><small>Shared world</small></span><span aria-hidden="true">•</span></div><div className="top-stat glass-button" aria-label={`${connectedCount} people in world`}><Icon name="people" size={19}/><b>{connectedCount} / 20</b></div><div className="connection-chip glass-button is-online" aria-label="Connected to world server"><span className="connection-light"/><b>Connected</b></div></div><div className="workspace-topbar__actions"><GlassButton className={`panel-trigger${activePanel==="people"?" is-active":""}`} data-panel-trigger onClick={onPeople} aria-label="People" aria-pressed={activePanel==="people"}><Icon name="people"/></GlassButton><GlassButton className={`panel-trigger${activePanel==="map"?" is-active":""}`} data-panel-trigger onClick={onMap} aria-label="Map" aria-pressed={activePanel==="map"}><Icon name="map"/></GlassButton><GlassButton className={`panel-trigger${activePanel==="invite"?" is-active":""}`} data-panel-trigger onClick={onInvite} aria-label="Invite" aria-pressed={activePanel==="invite"}><Icon name="link"/></GlassButton><GlassButton className={`panel-trigger${activePanel==="settings"?" is-active":""}`} data-panel-trigger onClick={onSettings} aria-label="Settings" aria-pressed={activePanel==="settings"}><Icon name="settings"/></GlassButton></div></header>}
function BottomDock({actions,onAction,micEnabled}){return <div className="bottom-dock glass-surface" style={{"--dock-count":actions.length}}>{actions.map(action=><GlassButton key={action.id} className={`dock-action dock-action--${action.id} ${action.id==="mic"&&!micEnabled?"is-muted":""}`} onClick={()=>onAction(action.id)} aria-label={action.id==="mic"?(micEnabled?"Mute microphone":"Enable microphone"):action.label}><Icon name={action.id==="mic"&&!micEnabled?"micOff":action.icon}/><small>{action.id==="mic"?(micEnabled?"Mute mic":"Enable mic"):action.label}</small></GlassButton>)}</div>}
function InvitePanel({inviteCode,onClose}){const [copied,setCopied]=useState(false);async function copy(){try{await navigator.clipboard.writeText(inviteCode);setCopied(true);setTimeout(()=>setCopied(false),1400)}catch{}}return <aside className="floating-panel invite-panel" data-panel-surface><div className="panel-heading"><div><span className="panel-kicker">INVITE TO WORLD</span><h2>Bring someone in.</h2></div><GlassButton onClick={onClose}>×</GlassButton></div><p className="invite-copy">Share this code. They can enter it from the Join a World screen.</p><div className="invite-code">{inviteCode}</div><button className="join-secondary invite-copy-button" onClick={copy}><Icon name="copy" size={16}/>{copied?"Copied":"Copy invite code"}</button></aside>}

export default function App(){
  const [playerName,setPlayerName]=useState("");const [inviteCode,setInviteCode]=useState("");const [worldName,setWorldName]=useState("");const [worldId,setWorldId]=useState("");const [worldInvite,setWorldInvite]=useState("");const [playerId,setPlayerId]=useState("");const [remotePlayers,setRemotePlayers]=useState([]);const [status,setStatus]=useState("Not connected");const [error,setError]=useState("");const [panel,setPanel]=useState(null);const [transparency,setTransparency]=useState(.68);const [micEnabled,setMicEnabled]=useState(false);const [micSupported,setMicSupported]=useState(false);const [micStream,setMicStream]=useState(null);
  const nameRef=useRef("");const intentRef=useRef(null);const lastSentRef=useRef(0);const panelRef=useRef(null);const micStreamRef=useRef(null);
  const {position,heading,activeKeys}=useMovement();
  useWebRTC({socket,playerId,micStream,remotePlayers,localPosition:position});
  useEffect(()=>{nameRef.current=playerName},[playerName]);
  useEffect(()=>{setMicSupported(Boolean(navigator.mediaDevices?.getUserMedia))},[]);
  useEffect(()=>{
    const closeOutside=e=>{if(!panel)return;if(e.target.closest?.("[data-panel-surface]")||e.target.closest?.("[data-panel-trigger]"))return;setPanel(null)};
    document.addEventListener("pointerdown",closeOutside);
    return()=>document.removeEventListener("pointerdown",closeOutside);
  },[panel]);
  useEffect(()=>{
    const onConnect=()=>{setStatus("Connected");const intent=intentRef.current;if(intent?.type==="create")socket.emit("create-world",{name:nameRef.current.trim()});if(intent?.type==="join")socket.emit("join-world",{name:nameRef.current.trim(),inviteCode:intent.code})};
    const onWorldCreated=payload=>{setWorldInvite(payload.inviteCode);setWorldName(payload.name)};
    const onWorldJoined=payload=>{setWorldId(payload.worldId);setWorldInvite(payload.inviteCode);setWorldName(payload.worldName);setPlayerId(payload.playerId);setRemotePlayers((payload.players||[]).filter(p=>p.playerId!==payload.playerId));setStatus("Joined");setError("")};
    const onPlayerJoined=player=>setRemotePlayers(prev=>prev.some(p=>p.playerId===player.playerId)?prev:[...prev,player]);
    const onPlayerMoved=payload=>setRemotePlayers(prev=>prev.map(p=>p.playerId===payload.playerId?{...p,...payload}:p));
    const onPlayerLeft=payload=>setRemotePlayers(prev=>prev.filter(p=>p.playerId!==payload.playerId));
    const onError=payload=>{setError(payload.message);setStatus("Join failed");intentRef.current=null;if(socket.connected)socket.disconnect()};
    const onDisconnect=()=>{if(worldId)setStatus("Disconnected")};
    socket.on("connect",onConnect);socket.on("world-created",onWorldCreated);socket.on("world-joined",onWorldJoined);socket.on("player-joined",onPlayerJoined);socket.on("player-moved",onPlayerMoved);socket.on("player-left",onPlayerLeft);socket.on("join-error",onError);socket.on("world-error",onError);socket.on("disconnect",onDisconnect);
    return()=>{socket.off("connect",onConnect);socket.off("world-created",onWorldCreated);socket.off("world-joined",onWorldJoined);socket.off("player-joined",onPlayerJoined);socket.off("player-moved",onPlayerMoved);socket.off("player-left",onPlayerLeft);socket.off("join-error",onError);socket.off("world-error",onError);socket.off("disconnect",onDisconnect)};
  },[worldId]);
  useEffect(()=>{if(!playerId||!socket.connected)return;const now=Date.now();if(now-lastSentRef.current<80)return;lastSentRef.current=now;socket.emit("player-moved",{x:position.x,y:position.y})},[position,playerId]);
  useEffect(()=>()=>{micStreamRef.current?.getTracks().forEach(track=>track.stop())},[]);
  async function toggleMic(){
    if(!micSupported){setError("This browser does not support microphone access.");return}
    if(!micStreamRef.current){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});micStreamRef.current=stream;setMicStream(stream);setMicEnabled(true);setError("")}catch{setError("Microphone permission was not granted.")}return}
    const next=!micEnabled;micStreamRef.current.getAudioTracks().forEach(track=>{track.enabled=next});setMicEnabled(next);
  }
  function togglePanel(next){setPanel(current=>current===next?null:next)}
  function begin(type){const name=playerName.trim();if(!name)return setError("Enter your display name.");if(name.length>20)return setError("Name must be between 1 and 20 characters.");if(type==="join"&&!inviteCode.trim())return setError("Enter the world invite code.");intentRef.current={type,code:inviteCode.trim().toUpperCase()};setError("");setStatus("Connecting…");if(socket.connected)socket.disconnect();socket.connect()}
  function leaveWorld(){socket.emit("leave-world");socket.disconnect();setWorldId("");setPlayerId("");setRemotePlayers([]);setWorldName("");setWorldInvite("");setPanel(null);setMicEnabled(false);setMicStream(null);micStreamRef.current?.getTracks().forEach(track=>track.stop());micStreamRef.current=null;intentRef.current=null;setStatus("Not connected")}
  const isJoined=Boolean(worldId&&playerId);const cssVars=useMemo(()=>({"--glass-alpha":transparency}),[transparency]);
  const actions=[];if(micSupported)actions.push({id:"mic",icon:"mic",label:"Microphone"});actions.push({id:"map",icon:"map",label:"Map"});if(remotePlayers.length>0)actions.push({id:"people",icon:"people",label:"People"});
  function handleDockAction(id){if(id==="mic")toggleMic();if(id==="map")togglePanel("map");if(id==="people")togglePanel("people")}
  return <main className={`workspace-app${isJoined?" workspace-app--joined":""}`} style={cssVars}>
    <div className="workspace-backdrop" aria-hidden="true"/><div className="workspace-world"><WorldCanvas position={position} heading={heading} playerName={playerName||"You"} remotePlayers={remotePlayers} showProximityZone={isJoined}/></div>
    {isJoined?<><TopBar worldName={worldName} connectedCount={remotePlayers.length+1} activePanel={panel} onPeople={()=>togglePanel("people")} onMap={()=>togglePanel("map")} onInvite={()=>togglePanel("invite")} onSettings={()=>togglePanel("settings")}/>
      <aside className="workspace-sidebar glass-surface"><div className="sidebar-nav"><div className="sidebar-nav__item is-active" aria-current="page"><Icon name="home"/><span>Lounge</span></div><button className={`sidebar-nav__item panel-trigger${panel==="people"?" is-active":""}`} data-panel-trigger onClick={()=>togglePanel("people")} aria-pressed={panel==="people"}><Icon name="people"/><span>People</span>{remotePlayers.length>0&&<b>{remotePlayers.length+1}</b>}</button><button className={`sidebar-nav__item panel-trigger${panel==="map"?" is-active":""}`} data-panel-trigger onClick={()=>togglePanel("map")} aria-pressed={panel==="map"}><Icon name="map"/><span>Map</span></button><button className={`sidebar-nav__item panel-trigger${panel==="settings"?" is-active":""}`} data-panel-trigger onClick={()=>togglePanel("settings")} aria-pressed={panel==="settings"}><Icon name="settings"/><span>Settings</span></button></div><div className="sidebar-room glass-inner"><div className="room-thumb">⌂</div><div><b>{worldName}</b><p>Your private spatial workspace.</p></div></div><button className="invite-button glass-button panel-trigger" data-panel-trigger onClick={()=>togglePanel("invite")}><Icon name="link" size={17}/> Invite People</button><div className="sidebar-people"><div className="sidebar-people__heading"><b>People in World ({remotePlayers.length+1})</b><Icon name="search" size={16}/></div><div className="sidebar-people__list"><div className="mini-person is-you"><Avatar name={playerName} tone="red" you/><span>{playerName} <em>YOU</em></span><i/></div>{remotePlayers.map(p=><div className="mini-person" key={p.playerId}><Avatar name={p.name}/><span>{p.name}</span><i/></div>)}</div>{remotePlayers.length===0&&<p className="sidebar-empty">There is no one here. Invite someone to your world.</p>}</div><button className="leave-world-button" onClick={leaveWorld}>Leave world</button></aside>
      <div className="world-range-label glass-inner"><span>Voice Range</span><b>{AUDIO_RADIUS}u</b><small>Visual only</small></div>
      <BottomDock actions={actions} onAction={handleDockAction} micEnabled={micEnabled}/>
      <div className="workspace-footer glass-inner"><span>Player <b>{playerId}</b></span><span>{Math.round(position.x)} × {Math.round(position.y)}</span><span>World {worldInvite}</span></div>
      {panel==="people"&&<PeoplePanel playerName={playerName} remotePlayers={remotePlayers} onClose={()=>setPanel(null)}/>} {panel==="map"&&<MiniMap position={position} remotePlayers={remotePlayers} onClose={()=>setPanel(null)}/>} {panel==="settings"&&<SettingsPanel transparency={transparency} setTransparency={setTransparency} onClose={()=>setPanel(null)}/>} {panel==="invite"&&<InvitePanel inviteCode={worldInvite} onClose={()=>setPanel(null)}/>}
    </>:<JoinWorld playerName={playerName} setPlayerName={setPlayerName} inviteCode={inviteCode} setInviteCode={setInviteCode} isConnecting={status==="Connecting…"} error={error} onCreate={()=>begin("create")} onJoin={()=>begin("join")}/>}
    <div className="sr-only" aria-live="polite">{activeKeys&&Object.keys(activeKeys).length?"Movement active":""}</div>
  </main>
}
